version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./frontend:/frontend
      - ./gdpr:/gdpr
    ports:
      - 80:80
    depends_on:
      - club_app
    environment:
      - PUID=1000
      - PGID=1000

  club_app: &app
    image: ghcr.io/umag/vas3k.club:latest
    command: make docker-run-dev
    container_name: club_app
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - PUID=1000
      - PGID=1000
    restart: always
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/frontend
      - ./gdpr/downloads:/app/gdpr/downloads

  queue:
    image: ghcr.io/umag/vas3k.club:latest
    command: make docker-run-queue
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - PUID=1000
      - PGID=1000
    restart: always
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vas3k_club
      - PUID=1000
      - PGID=1000
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PUID=1000
      - PGID=1000
    ports:
      - 6379:6379
